"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { AlertCircle, CheckCircle2, Loader2, MailCheck, RefreshCw } from "lucide-react";
import { resendVerification, verifyEmail } from "@/lib/api/client";

export function VerifyEmailForm(){
  const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
  useEffect(()=>{ const params=new URLSearchParams(window.location.search); setEmail(params.get('email') || ''); },[]);
  async function submit(e:FormEvent){ e.preventDefault(); setError(''); setSuccess(''); setBusy(true); try{ await verifyEmail({email,code}); setSuccess('Email verified. Redirecting to login...'); setTimeout(()=>{window.location.href='/auth/login'},700); }catch(err:any){setError(err.message||'Verification failed.')} finally{setBusy(false);} }
  async function resend(){ setError(''); setSuccess(''); setBusy(true); try{ await resendVerification({email}); setSuccess('If this email has an unverified account, a new code has been sent.'); }catch(err:any){setError(err.message||'Could not resend code.')} finally{setBusy(false);} }
  return <div className="card mx-auto max-w-md p-6 sm:p-8 animate-soft-pop"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-emerald-50 text-success"><MailCheck className="h-5 w-5"/></span><h1 className="mt-5 text-3xl font-bold text-ink">Verify your email</h1><p className="mt-2 text-sm leading-6 text-subtle">Enter the verification code sent to your email address. You can log in after verification.</p><form className="mt-6 space-y-4" onSubmit={submit}><label className="block text-sm font-semibold text-ink">Email<input className="input mt-2" value={email} onChange={(e)=>setEmail(e.target.value)} type="email" required/></label><label className="block text-sm font-semibold text-ink">Verification code<input className="input mt-2 text-center text-2xl font-bold tracking-[0.35em]" value={code} onChange={(e)=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" placeholder="000000" required/></label>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-danger"><AlertCircle className="mr-2 inline h-4 w-4"/>{error}</div>}{success&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-semibold text-emerald-800"><CheckCircle2 className="mr-2 inline h-4 w-4"/>{success}</div>}<button className="btn btn-primary w-full" disabled={busy}>{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}Verify email</button><button type="button" className="btn btn-secondary w-full" onClick={resend} disabled={busy || !email}><RefreshCw className="h-4 w-4"/>Resend code</button></form><p className="mt-5 text-center text-sm text-subtle"><Link className="font-bold text-brand" href="/auth/login">Back to login</Link></p></div>
}
